version: "3"
services:
  web10:
    image: httpd:latest
    ports:
      - "9010:80"
    volumes:
      - /home:/usr/local/apache2/htdocs

  web2:
    image: httpd:latest
    ports:
      - "9020:80"
    volumes:
      - /home:/usr/local/apache2/htdocs

  web3:
    image: httpd:latest
    ports:
      - "9030:80"
    volumes:
      - /home:/usr/local/apache2/htdocs
